Repository gip-inclusion/rdv-insertion, pull requests merged in 2021-11, with the labels that each got.

#108 Front/Redesign landing page
  .eslintignore
  app/javascript/fonts/Marianne/Marianne-Regular.woff
  app/javascript/images/illustrations/calendar.svg
  app/javascript/images/illustrations/choice.svg
  app/javascript/images/illustrations/computer.svg
  app/javascript/images/illustrations/letter.svg
  app/javascript/images/illustrations/welcome-illustration.svg
  app/javascript/images/logos/rdvi-favicon.png
  app/javascript/stylesheets/_fonts.scss
  app/javascript/stylesheets/_variables.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/components/_button.scss
  app/javascript/stylesheets/components/_card.scss
  app/javascript/stylesheets/components/_color.scss
  app/javascript/stylesheets/components/_footer.scss
  app/javascript/stylesheets/components/_form.scss
  app/javascript/stylesheets/components/_image.scss
  app/javascript/stylesheets/components/_navbar.scss
  app/javascript/stylesheets/components/_title.scss
  app/views/common/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/sessions/_login_form.html.erb
  app/views/static_pages/welcome.html.erb
Labels: enhancement, RDV-Insertion

#106 refactor(app): create organisations [1/4]
  app/controllers/applicants_controller.rb
  app/controllers/invitations_controller.rb
  app/javascript/react/actions/inviteApplicant.js
  app/javascript/react/actions/searchApplicants.js
  app/javascript/react/components/Applicant.jsx
  app/javascript/react/pages/ApplicantsUpload.jsx
  app/jobs/notify_applicant_job.rb
  app/jobs/process_rdv_solidarites_webhook_job.rb
  app/models/applicant.rb
  app/models/department.rb
  app/models/invitation.rb
  app/policies/department_policy.rb
  app/services/concerns/notifications/rdv_concern.rb
  app/services/create_applicant.rb
  app/services/invitations/create.rb
  app/services/invitations/invite_applicant.rb
  app/services/invitations/retrieve_or_create.rb
  app/services/notifications/notify_applicant.rb
  app/services/notifications/rdv_cancelled.rb
  app/services/notifications/rdv_created.rb
  app/services/refresh_applicants.rb
  app/views/mailers/invitation_mailer/first_invitation.html.erb
  config/routes.rb
  db/migrate/20211020141004_add_department_applicants.rb
  db/migrate/20211020145820_add_department_to_invitation.rb
  db/schema.rb
  spec/controllers/applicants_controller_spec.rb
  spec/controllers/invitations_controller_spec.rb
  spec/factories/applicant.rb
  spec/factories/invitation.rb
  spec/jobs/notify_applicant_job_spec.rb
  spec/jobs/process_rdv_solidarites_webhook_job_spec.rb
  spec/mailers/invitation_mailer_spec.rb
  spec/services/create_applicant_spec.rb
  spec/services/invitations/create_spec.rb
  spec/services/invitations/invite_applicant_spec.rb
  spec/services/invitations/retrieve_or_create_spec.rb
  spec/services/invitations/send_sms_spec.rb
  spec/services/notifications/notify_applicant_spec.rb
  spec/services/notifications/rdv_cancelled_spec.rb
  spec/services/notifications/rdv_created_spec.rb
  spec/services/refresh_applicants_spec.rb
Labels: Refactor

#112 refactor(app): Create organisations [3/4]
  .rubocop.yml
  db/migrate/20211102161424_change_department_table.rb
  db/schema.rb
  spec/mailers/invitation_mailer_spec.rb
  spec/services/invitations/create_spec.rb
Labels: Refactor

#113 refactor(app): Create organisations [4/4]
  app/javascript/react/pages/ApplicantsUpload.jsx
  app/javascript/stylesheets/components/_card.scss
  app/javascript/stylesheets/components/_title.scss
  app/models/department.rb
  app/models/organisation.rb
  app/services/invitations/compute_link.rb
  app/services/notifications/rdv_created.rb
  app/services/notifications/rdv_updated.rb
  app/views/applicants/index.html.erb
  app/views/organisations/index.html.erb
  app/views/uploads/new.html.erb
  db/migrate/20211102171611_change_organisations.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/department.rb
  spec/factories/organisation.rb
  spec/services/invitations/compute_link_spec.rb
  spec/services/invitations/send_sms_spec.rb
  spec/services/notifications/rdv_cancelled_spec.rb
  spec/services/notifications/rdv_created_spec.rb
Labels: Refactor

#110 Feat/Add warnings with errors for applicants file upload
  app/javascript/lib/getKeyByValue.js
  app/javascript/lib/parameterize.js
  app/javascript/react/pages/ApplicantsUpload.jsx
  app/javascript/stylesheets/components/_footer.scss
  db/seeds.rb
Labels: enhancement, RDV-Insertion, Création du compte

#129 Fix/Translate rdv-solidarites errors in french
  app/services/rdv_solidarites_api/base.rb
  app/services/rdv_solidarites_api/create_user.rb
  app/services/rdv_solidarites_api/retrieve_invitation_token.rb
  app/services/rdv_solidarites_api/retrieve_motifs.rb
  app/services/rdv_solidarites_api/retrieve_resources.rb
  app/services/rdv_solidarites_api/retrieve_user.rb
  spec/services/rdv_solidarites_api/create_user_spec.rb
  spec/services/rdv_solidarites_api/retrieve_invitation_token_spec.rb
  spec/services/rdv_solidarites_api/retrieve_motifs_spec.rb
  spec/services/rdv_solidarites_api/retrieve_resources_spec.rb
  spec/services/rdv_solidarites_api/retrieve_user_spec.rb
Labels: bug, RDV-Solidarités, RDV-Insertion
