Repository gip-inclusion/rdv-insertion, pull requests merged in 2021-09, with the labels that each got.

#35 chore(deps): update dependencies
  .ruby-version
  Gemfile
  Gemfile.lock
  app/services/invitations/compute_link.rb
  app/services/invitations/send_sms.rb
  spec/rails_helper.rb
  spec/services/invitations/send_sms_spec.rb
Labels: dependencies

#39 feat(yonne): Add Yonne page
  app/controllers/applicants_controller.rb
  app/javascript/images/maps/yonne.svg
  app/javascript/react/components/Applicant.jsx
  app/javascript/react/lib/formatPhoneNumber.js
  app/javascript/react/models/Applicant.js
  app/javascript/react/pages/Applicants.jsx
  app/services/base_service.rb
  db/migrate/20210902122939_add_column_names_to_configuration.rb
  db/migrate/20210902131848_add_custom_id_to_applicants.rb
  db/schema.rb
Labels: enhancement

#42 Updating seeds
  db/seeds.rb
Labels: Feature technique

#43 Feat/Raccourcir le lien d'invitation envoyé au bRSA
  .env.example
  app/controllers/invitations_controller.rb
  app/services/invitations/send_sms.rb
  config/routes.rb
  db/migrate/20210907172021_add_seen_to_invitations.rb
  db/schema.rb
  spec/controllers/invitations_controller_spec.rb
  spec/services/invitations/send_sms_spec.rb
Labels: enhancement, RDV-Insertion, Création du compte

#59 Feat/Sentry
  .env.example
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  config/initializers/sentry.rb
  dump.rdb
  package.json
  yarn.lock
Labels: enhancement, Feature technique

#65 Feat/Rendre la page d'accueil RDV-Insertion responsive
  .gitignore
  app/controllers/departments_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/static_pages_controller.rb
  app/javascript/images/logos/rdv-insertion.png
  app/javascript/stylesheets/_fontawesome_imports.scss
  app/javascript/stylesheets/_variables.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/components/_card.scss
  app/javascript/stylesheets/components/_footer.scss
  app/javascript/stylesheets/components/_navbar.scss
  app/policies/department_policy.rb
  app/views/common/_footer.html.erb
  app/views/common/_header.html.erb
  app/views/departments/index.html.erb
  app/views/static_pages/welcome.html.erb
  config/routes.rb
  dump.rdb
  package.json
  spec/controllers/departments_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/static_pages_controller_spec.rb
  yarn.lock
Labels: enhancement, RDV-Insertion, Création du compte
