Repository gip-inclusion/rdv-insertion, pull requests merged in 2023-07, with the labels that each got.

#1157 Ajouter le logo de l'orga La Ressource AAA
  app/javascript/images/logos/la-ressource-aaa.jpg
Labels: RDV-Insertion

#1200 Change aveyron logo
  app/javascript/images/logos/aveyron.jpg
Labels: RDV-Insertion

#1201 Delete aveyron.png
  app/javascript/images/logos/aveyron.png
Labels: RDV-Insertion

#1202 Delete aveyron.svg
  app/javascript/images/logos/aveyron.svg
Labels: RDV-Insertion

#1210 fix(upload): Fix contacts data update
  app/javascript/react/components/applicant/ContactInfosExtraLine.jsx
  app/javascript/react/lib/updateApplicantContactsData.js
Labels: bug

#1213 feat(upload): Add feature tests for contact file upload
  app/javascript/react/components/Applicant.jsx
  app/javascript/react/components/EnrichWithContactFile.jsx
  app/javascript/react/components/FileHandler.jsx
  app/javascript/react/models/Applicant.js
  app/javascript/react/pages/ApplicantsUpload.jsx
  spec/features/agent_can_archive_and_unarchive_applicant_spec.rb
  spec/features/agent_can_create_carnet_spec.rb
  spec/features/agent_can_update_contacts_info_spec.rb
  spec/features/agent_can_upload_applicant_list_spec.rb
  spec/fixtures/fichier_contact_test.csv
Labels: Feature technique

#1241 feat(upload): display invalid applicants firsts
  app/javascript/react/components/ApplicantList.jsx
  app/javascript/react/models/Applicants.js
  app/javascript/react/pages/ApplicantsUpload.jsx
Labels: enhancement, javascript
