Repository gip-inclusion/rdv-insertion, pull requests merged in 2024-03, with the labels that each got.

#1817 logo colombbus suresnes
  app/assets/images/logos/colombbus-suresnes.png
Labels: rdv-insertion

#1796 feat(app): Handle better deleted users
  app/models/user.rb
  app/services/users/sync_with_rdv_solidarites.rb
  db/migrate/20240226140143_add_old_rdv_solidarites_user_id_to_users.rb
  db/schema.rb
Labels: Feature technique

#1869 fix(mails): avoid images "explosion" in outlook
  app/assets/images/logos/france-travail.png
  app/javascript/stylesheets/mail.scss
  app/views/layouts/mailer.html.erb
  app/views/mailers/_logos.html.erb
Labels: bug

#1888 fix(front): small requested changes
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/components/_table.scss
  app/views/rdv_contexts/_close_rdv_context_button.html.erb
  app/views/users/_all_users_table.html.erb
  app/views/users/_archived_users_table.html.erb
  app/views/users/_users_list_header.html.erb
  spec/features/agent_can_close_or_reopen_rdv_context_spec.rb
Labels: UI/UX
